### PR TITLE
make the tagger tag main where appropriate

### PR DESCRIPTION
**Pull request by blizzz**
That solution is not very awesome, but rather pragmatic. Branch might be left out in the command with "master", but I am not sure about the historic tagging, and lack time for testing.

### CODE REVIEW

**Comment by nickvergessen** [comment]
```sh
DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
```

I use this in my scripts and it works greatly. However in the release org where main is the "frontpage" and not the code and still the default branch that would fail.

**Review by skjnldsv — COMMENTED** [review]
We should find a different way.
There are ways to tag something with the API only

1. Create a release
2. Delete the release
3. See the tag remain

**Review by juliushaertl — APPROVED** [review]
Looks good to me 👍

**Comment by nickvergessen** [comment]
Rebased and added another "main" app

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
